name: Node.js Package nikhil
run-name: Deploy ${{ inputs.application }} config to ${{ inputs.environment }} by @${{ github.actor }} 
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Env'
        default: 'dev' 
        type: choice
        options:
        - prod
        - prodFedRAMP
        - dev 
      application:
        description: 'Env'
        default: 'Twistlock' 
        type: choice
        options:
        - sumologic
        - twistlock
        - redlock

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - run: terraform init
